function CategoryHologram({
  hologramRef,
  infoRef,
  imageRef,
  buttonRef,
  pageButtonRef,
}) {
  return (
    <div
      ref={hologramRef}
      className="
        pointer-events-none
        absolute
        z-20
        h-0
        w-0
        opacity-0
        transition-opacity
        duration-300
        ease-out
      "
    >
      <div
        className="
          holo-panel
          hologram-image-panel
          absolute
          right-[220px]
          top-1/2
          w-[min(44vw,420px)]
          -translate-y-1/2
          overflow-hidden
          p-4
          sm:right-[260px]
          sm:p-5
        "
      >
        <div className="holo-scan" />

        <div
          className="
            mb-3
            font-mono
            text-[9px]
            tracking-[0.25em]
            text-cyan-200
            sm:text-xs
          "
        >
          VISUAL DATA
        </div>

        <img
          ref={imageRef}
          src=""
          alt=""
          className="
            aspect-video
            w-full
            object-cover
            opacity-80
          "
        />
      </div>

      <div
        className="
          holo-panel
          hologram-info-panel
          absolute
          left-[180px]
          top-1/2
          w-[min(44vw,440px)]
          -translate-y-1/2
          p-5
          sm:left-[210px]
          sm:p-6
        "
      >
        <div className="holo-scan" />

        <div
          className="
            mb-3
            font-mono
            text-[9px]
            tracking-[0.25em]
            text-cyan-200
            sm:text-xs
          "
        >
          FIELD DATA
        </div>

        <p
          ref={infoRef}
          className="
            font-mono
            text-[11px]
            leading-relaxed
            text-cyan-50
            sm:text-sm
          "
        />

        <a
          ref={pageButtonRef}
          href="#"
          className="
            hologram-page-button
            pointer-events-auto
            mt-6
            hidden
            w-full
            items-center
            justify-center
            gap-3
            whitespace-nowrap
            font-mono
            text-sm
            font-bold
            tracking-[0.14em]
          "
        >
          <span
            className="
              hologram-page-button-icon
              text-lg
              leading-none
            "
          >
            ▶
          </span>

          <span>
            ページへ移動
          </span>
        </a>
      </div>

      <button
        ref={buttonRef}
        type="button"
        className="
          hologram-expand-button
          pointer-events-auto
          absolute
          left-1/2
          top-8
          flex
          -translate-x-1/2
          translate-y-full
          flex-row
          items-center
          gap-2
          whitespace-nowrap
          border-0
          bg-transparent
          p-0
          font-mono
          text-sm
          font-semibold
          tracking-[0.12em]
          text-cyan-200
          transition-colors
          duration-200
          hover:text-white
          sm:top-10
          sm:gap-3
          sm:text-base
        "
      >
        <span
          className="
            text-xl
            leading-none
            sm:text-2xl
          "
        >
          △
        </span>

        <span>
          拡大
        </span>
      </button>
    </div>
  )
}

export default CategoryHologram